language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
script: yarn export
before_deploy : touch out/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: out
  on:
    branch: master
